# Generated by Django 3.0.9 on 2020-08-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcore', '0002_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('caption', models.CharField(max_length=50)),
                ('story', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('draft', models.BooleanField(default=True)),
                ('visible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
    ]
