# Generated by Django 3.0.9 on 2020-08-07 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcore', '0003_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='extract',
            field=models.CharField(default='some stuff', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='image_file',
            field=models.FilePathField(blank=True),
        ),
    ]
