# Generated by Django 3.0.9 on 2020-08-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcore', '0008_auto_20200810_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_file',
            field=models.FileField(blank=True, null=True, upload_to='blog_image'),
        ),
    ]
