# Generated by Django 3.0.9 on 2020-08-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcore', '0011_services_descrip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('image_file', models.FileField(blank=True, null=True, upload_to='service_icon')),
                ('descrip', models.CharField(blank=True, max_length=300, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='project',
            field=models.BooleanField(default=False),
        ),
    ]
