# Generated by Django 3.0.9 on 2020-08-14 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcore', '0012_auto_20200812_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='sector',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
