# Generated by Django 3.0.9 on 2020-08-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcore', '0013_customer_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_file',
            field=models.FileField(blank=True, null=True, upload_to='blog_article'),
        ),
    ]
