# Generated by Django 3.0.9 on 2020-08-07 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcore', '0004_auto_20200807_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image_file',
        ),
    ]
