# Generated by Django 3.0.9 on 2020-08-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcore', '0009_article_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='image_file',
            field=models.FileField(blank=True, null=True, upload_to='service_icon'),
        ),
    ]
