# Generated by Django 3.0.9 on 2020-08-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcore', '0010_services_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='descrip',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
