# Generated by Django 3.0.9 on 2020-08-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcore', '0014_article_article_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=50, unique=True)),
                ('image_file', models.FileField(blank=True, null=True, upload_to='feature_icon')),
                ('descrip', models.CharField(blank=True, max_length=200, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['feature'],
            },
        ),
    ]
